---

- hosts: datacenter
  become: true

  tasks:
    - name: generate /etc/hosts file
      ansible.builtin.template:
        src: ../templates/hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'

- name: Running SSL Playbook
  import_playbook: SSL.yml

- name: Running install servers NGINX Playbook
  import_playbook: webservers.yml

- name: Running install loadbalancers NGINX Playbook
  import_playbook: loadbalancer.yml

- name: Running install databases Playbook
  import_playbook: databases.yml
